In [80]:
import pandas as pd
import numpy as np

In [81]:
df = pd.read_csv("DataScience QA.csv")

In [82]:
df.sample(8)

,Question,Answer
129,What is exploration in reinforcement learning?,Exploration is the process of actively seeking...
89,What is the Apriori algorithm?,The Apriori algorithm is a classic algorithm f...
100,What is the purpose of generative modeling?,Generative modeling is used to model the under...
121,What is an agent in reinforcement learning?,An agent is the entity that learns to make dec...
118,What is the Expectation-Maximization (EM) algo...,The Expectation-Maximization (EM) algorithm is...
50,What is the purpose of the A/B test in data sc...,A/B testing is a statistical hypothesis testin...
26,What are the main components of the data scien...,"The main components include data collection, d..."
69,What is batch normalization in neural networks?,Batch normalization is a technique used to nor...

In [83]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Question  158 non-null    str
 1   Answer    158 non-null    str
dtypes: str(2)
memory usage: 43.3 KB

In [84]:
df.shape

(158, 2)

In [85]:
df.isnull().sum()

Question    0
Answer      0
dtype: int64

In [86]:
df.duplicated().sum()

np.int64(12)

In [87]:
df.drop_duplicates(inplace=True)

In [88]:
import re
from nltk.corpus import stopwords

def clean_data(text):
    text = text.lower()
    text = re.sub(r"[^a-zA-Z0-9]", ' ', text) # remove special characters
    text = re.sub(r"\s+", ' ', text) # remove extra spaces
    text = ' '.join([word for word in text.split() if word not in (stopwords.words('english'))])
    return text

In [89]:
df['Question'] = df['Question'].apply(clean_data)

In [90]:
df.sample(8)

,Question,Answer
149,policy learning,On-policy learning is a learning method in rei...
19,self supervised learning,Self-supervised learning is a form of unsuperv...
2,difference batch processing real time processing,Batch processing involves processing data in l...
90,fp growth,FP-Growth (Frequent Pattern Growth) is an effi...
40,explain difference pca sne,PCA (Principal Component Analysis) is a linear...
20,reinforcement learning,Reinforcement learning is a type of machine le...
54,purpose hypothesis testing,Hypothesis testing is used to make inferences ...
131,exploration exploitation trade reinforcement l...,The exploration-exploitation trade-off refers ...

In [91]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(ngram_range=(1, 2), max_features=400)
X = vectorizer.fit_transform(df['Question'])
y = df['Answer']

In [92]:
X.shape

(146, 400)

In [93]:
y.shape

(146,)

In [94]:
df = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
df['Answer'] = y
df.shape

(146, 401)

In [95]:
df.isnull().sum()

activation               0
activation functions     0
actor                    0
actor critic             0
advantage                0
                        ..
value                    0
value decomposition      0
value function           0
variance                 0
Answer                  12
Length: 401, dtype: int64

In [96]:
df.duplicated().sum()

np.int64(2)

In [98]:
df.drop_duplicates(inplace=True)
df.dropna(inplace=True)
df.shape

(134, 401)